Draft: Iw4x integration
XLabsProject/launcher pull request #197
Opened 2022-01-03 12:16 UTC by Rackover

2022-01-11 14:29 UTC, diamante0018 reviewed
Sometimes you write `std::string data{}` other times you omit the `{}`, it doesn't change the behaviour of the code but I noticed it.
Otherwise, the code doesn't seem wrong. I will test it when I can to see if it works.

2022-01-11 14:29 UTC, diamante0018 commented on src/launcher/updater/file_updater.cpp
> +			return true;
so if an error occurs iw4x does require an update? (Reading function name)

2022-01-11 14:29 UTC, diamante0018 commented on src/launcher/updater/file_updater.cpp
> +			return true;
So if file can't be read iw4x requires an update? (Reading function name)

2022-01-11 14:34 UTC, Rackover commented on src/launcher/updater/file_updater.cpp
> +			return true;
Correct

2022-01-11 14:35 UTC, Rackover commented on src/launcher/updater/file_updater.cpp
> +			return true;
Yes same, if version cannot be determined we need to update, so that we're sure, and then we write down the version anyway

2022-01-12 05:56 UTC, momo5502 requested changes
The hack for iw4x is fine, but should be adjusted in the future, however downloading the files only when necessary is definitely a good thing. I think github cdn has a quota. So you might get to a point where users won't be able to download anything anymore, that's why everything else is on the vps, but we'll see if we reach that quota

2022-01-12 05:56 UTC, momo5502 commented on .gitmodules
> +[submodule "deps/andyzip"]
zlib has a module integrated called minizip, it's widely used throughout iw6x/s1x. I'd prefer minizip over this tbh.

2022-01-12 05:56 UTC, momo5502 commented on src/launcher/updater/file_updater.hpp
> +		struct iw4x_update_state {
formatting

2022-01-12 10:22 UTC, Rackover commented on .gitmodules
> +[submodule "deps/andyzip"]
I swapped andyzip for zlib but now unzipping a file takes up about 60 lines instead of 5, and i feel like this is a big load of boilerplate for unzipping a single file in a single place in the project and nowhere else. If you are okay with that it's good to me, but are you sure?  (I may have overthought it)

566715a4508cfb562afe0ef35e4ea3774b7b28f1

2022-01-14 06:34 UTC, momo5502 approved these changes
I'll approve this, but you can swap out zlib for andyzip again if you think it's better. I like zlib because it's thoroughly tested and fuzzed, but if you want less lines instead, feel free to change it.

2022-01-14 06:36 UTC, momo5502 commented
Once the draft from the title is removed, i will merge it

2022-01-14 10:55 UTC, Rackover commented
I trust you with zlib :) 
Ready to be merged. Will the deployment of the new version of the launcher on masterxlabs done automatically for the launcher, or will someone have to upload it?

2022-01-14 11:03 UTC, merged