Curl fail on error so we get explicit messages in case we hit github rate limit (or else)
XLabsProject/launcher pull request #227
Opened 2022-01-31 09:27 UTC by Rackover

2022-02-04 11:21 UTC, diamante0018 requested changes
It's good you made such an addition to the code. Please see my comment

2022-02-04 11:21 UTC, diamante0018 commented on src/common/utils/http.cpp
> +			throw std::exception(("Bad status code "+std::to_string(http_code)+" met while trying to download file "+url+"!").c_str());
Uh, aren't you looking for std::runtime_error ?
You are using a non-standard implementation for std::exception as there is no constructor according to the good old C++ standard that takes a "const char*" as parameter.
https://en.cppreference.com/w/cpp/error/exception/exception

2022-02-06 10:50 UTC, momo5502 requested changes

2022-02-06 10:50 UTC, momo5502 commented on src/common/utils/http.cpp
> +			}
You shouldn't get any 302 or 301, cause of CURLOPT_FOLLOWLOCATION

2022-02-06 10:50 UTC, momo5502 commented on src/common/utils/http.cpp
> +			throw std::exception(("Bad status code "+std::to_string(http_code)+" met while trying to download file "+url+"!").c_str());
Yup, std::runtime_error is needed here

2022-02-09 14:34 UTC, Rackover commented
I think it's ready. the >200 check is a bit extra but it should work

2022-02-21 19:38 UTC, momo5502 approved these changes

2022-02-21 19:38 UTC, merged