Remove manual DPI-Aware calculation, disable CEF DPI-awareness and us…
XLabsProject/launcher pull request #296
Opened 2022-04-20 10:12 UTC by Rackover

…e only Windows' DPI awareness functions. This makes sure we don't get wrong calculations whenever DPI is adjusted (Tested)

2022-04-20 10:12 UTC, Rackover commented
This fixes a common bug where people get an all zoomed out launcher that they cannot use. Can be easily reproduced by messing with DPI in windows settings while the window is open.

2022-04-20 12:39 UTC, diamante0018 approved these changes

2022-04-20 12:39 UTC, diamante0018 commented on src/launcher/main.cpp
> +		else if (SetProcessDPIAware()) {
😄

2022-04-20 16:58 UTC, Rackover commented on src/launcher/main.cpp
> -		if (set_dpi)
You're right didn't think of that, this should be fixed now

2022-04-29 06:18 UTC, momo5502 requested changes

2022-04-29 06:18 UTC, momo5502 commented on src/launcher/main.cpp
> +				SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);
this will add an import which cannot be resolved. the the os checks are obsolete as it will be broken on old versions. you need the dll load approach as it was done previously

2022-04-29 06:18 UTC, momo5502 commented on src/launcher/main.cpp
> +				SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);
and then you can simply check if set_dpi was resolved, if not call the vista function. no complex version checks

2022-04-29 06:18 UTC, momo5502 commented on src/launcher/cef/cef_ui.cpp
> +		window_info.style = WS_SIZEBOX | WS_POPUP;
nice

2022-05-01 08:28 UTC, momo5502 commented on src/launcher/std_include.hpp
> +#pragma comment(lib, "Shcore.lib")
is this still needed?

2022-05-01 08:28 UTC, momo5502 commented on src/launcher/std_include.hpp
> +#include <shellscalingapi.h>
still needed?

2022-05-01 09:11 UTC, diamante0018 commented on src/launcher/std_include.hpp
> +#include <shellscalingapi.h>
I used the macro PROCESS_PER_MONITOR_DPI_AWARE at line 69 of main.cpp. I can replace it with an integer if you don't want it since it evaluates to 2

2022-05-01 09:14 UTC, diamante0018 commented on src/launcher/std_include.hpp
> +#pragma comment(lib, "Shcore.lib")
I don't think so I'll remove it

2022-05-01 09:20 UTC, momo5502 approved these changes

2022-05-01 09:20 UTC, merged