Added a minimal logger so we know what's going on with iw4x updates p…
XLabsProject/launcher pull request #298
Opened 2022-04-20 16:23 UTC by Rackover

…ermanently stuck

2022-04-20 16:39 UTC, diamante0018 requested changes
I like this change
Please be consinstent with your style of string concatenation
Sometimes it's like `"..."+val+"..."` other times there is a space between the `+` and the `"`

2022-04-20 16:39 UTC, diamante0018 commented on src/common/utils/logger.cpp
> +std::mutex utils::logger::lock;
Have you checked out the other class utils class named_mutex?
There are examples on how to use it in the repo.

2022-04-20 16:39 UTC, diamante0018 commented on src/common/utils/logger.cpp
> +	lock.lock();
Not ideal, I feel this should be used in conjunction with named mutex class with the std::unique_lock wrapper so it does all the good RAII stuff

2022-04-29 16:24 UTC, diamante0018 commented
After some time spent googling  I decided to keep static inline in the header because it should make the compiler inline the calls to the function which is what we want if the std::source_location to be accurate

2022-04-29 19:34 UTC, diamante0018 commented on src/common/utils/logger.cpp
> +				log_file_stream << line << std::endl;
the try catch is for the exceptions that << overloaded function may (don't know which but I don't trust io functions) throw it's not to check if the stream is open or not. 
I will add a check to see if the stream is open.
If an exceptions is caught it a messagebox can be displayed i guess

2022-05-01 08:30 UTC, momo5502 approved these changes

2022-05-01 10:51 UTC, merged