DRAFT: Wstring non ascii usernames support
XLabsProject/launcher pull request #307
Opened 2022-04-30 17:13 UTC by Rackover

For our friends with non-ASCII characters in their windows username
This works, as in CEF loads and everything, but then it can't create GPU context.

```
[0430/185204.174:ERROR:gpu_channel_manager.cc(748)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[0430/185204.174:ERROR:shared_image_stub.cc(532)] SharedImageStub: unable to create context
[0430/185204.174:ERROR:gpu_channel.cc(570)] GpuChannel: Failed to create SharedImageStub
[0430/185204.174:ERROR:gpu_channel_manager.cc(748)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[0430/185204.174:ERROR:shared_image_stub.cc(532)] SharedImageStub: unable to create context
[0430/185204.174:ERROR:gpu_channel.cc(570)] GpuChannel: Failed to create SharedImageStub
[0430/185204.174:ERROR:gpu_channel_manager.cc(748)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[0430/185204.174:ERROR:shared_image_stub.cc(532)] SharedImageStub: unable to create context
[0430/185204.174:ERROR:gpu_channel.cc(570)] GpuChannel: Failed to create SharedImageStub
[0430/185204.174:ERROR:gpu_channel_manager.cc(748)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[0430/185204.174:ERROR:shared_image_stub.cc(532)] SharedImageStub: unable to create context
[0430/185204.174:ERROR:gpu_channel.cc(570)] GpuChannel: Failed to create SharedImageStub
[0430/185204.174:ERROR:gpu_channel_manager.cc(748)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[0430/185204.174:ERROR:shared_image_stub.cc(532)] SharedImageStub: unable to create context
[0430/185204.174:ERROR:gpu_channel.cc(570)] GpuChannel: Failed to create SharedImageStub
[0430/185204.174:ERROR:gpu_channel_manager.cc(748)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[0430/185204.174:ERROR:shared_image_stub.cc(532)] SharedImageStub: unable to create context
[0430/185204.174:ERROR:gpu_channel.cc(570)] GpuChannel: Failed to create SharedImageStub
[0430/185204.174:ERROR:gpu_channel_manager.cc(748)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[0430/185204.174:ERROR:shared_image_stub.cc(532)] SharedImageStub: unable to create context
...
```

not sure why yet!

2022-04-30 20:21 UTC, diamante0018 requested changes
Good changes, minor things to address.

2022-04-30 20:21 UTC, diamante0018 commented on src/common/utils/nt.cpp
> +		if (!this->is_valid()) return L"";
Replace `L""` with `{}`

2022-04-30 20:21 UTC, diamante0018 commented on src/common/utils/io.cpp
>  		return std::ifstream(file).good();
I know you did not write this bit but std::filesystem::exists is a good option

2022-04-30 20:21 UTC, diamante0018 commented on src/common/utils/nt.cpp
>  		if (!this->is_valid()) return "";
Would prefer `{}` instead of `""` here as well. (Empty path which is totally valid)

2022-04-30 20:21 UTC, diamante0018 commented on src/common/utils/nt.cpp
> +		SetDllDirectoryW(directory.wstring().c_str());
.data() is preferred in xlabs code

2022-04-30 20:21 UTC, diamante0018 commented on src/common/utils/nt.cpp
> +	std::filesystem::path library::get_dll_directory()
perhaps make this function use Wide version of winapi calls?

2022-04-30 20:21 UTC, diamante0018 commented on src/common/utils/nt.cpp
> +	void launch_process(const std::filesystem::path& process, std::string command_line)
replace std::string command_line with a wide string so you don't have to use codecvt

2022-04-30 20:21 UTC, diamante0018 commented on src/common/utils/nt.hpp
> +#include <codecvt>
Not needed anymore if the previous point in launch_process is addresses

2022-04-30 20:21 UTC, diamante0018 commented on src/launcher/cef/cef_ui_scheme_handler.cpp
> +		while (path[0] == '/') {
You already know

2022-04-30 20:21 UTC, diamante0018 commented on src/launcher/cef/cef_ui_scheme_handler.cpp
> +		if (utils::io::read_file(file, &content)) {
same

2022-04-30 20:21 UTC, diamante0018 commented on src/launcher/main.cpp
> +		auto fsPath = std::filesystem::path(path) / "xlabs";
snake case please

2022-04-30 20:21 UTC, diamante0018 commented on src/launcher/main.cpp
> +		std::filesystem::current_path(appdata);
good addition. replacing unportable winapi calls with modern c++ code is nice

2022-04-30 20:21 UTC, diamante0018 commented on src/launcher/updater/file_updater.cpp
> +		unzFile file = unzOpen(reinterpret_cast<const char*>(rawfiles_zip.wstring().c_str()));
this is probably not dieal. I suggest using utils::string::convert.

2022-04-30 20:21 UTC, diamante0018 commented on premake5.lua
> +	defines {"_WINDOWS", "WIN32", "_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING"}
Woud have put this in std_include. Reason why it's deprecated is another good reason as to why you should not use it.

2022-04-30 20:21 UTC, diamante0018 commented on src/common/utils/nt.cpp
> +	void launch_process(const std::filesystem::path& process, std::string command_line)
Subsequently replace calls to getcommandlineA with the wide version. That should fix the problem

2022-04-30 20:38 UTC, Rackover commented on src/launcher/updater/file_updater.cpp
> +		unzFile file = unzOpen(reinterpret_cast<const char*>(rawfiles_zip.wstring().c_str()));
i'm not sure yet. minizip _might_ support wchar arrays casted as char arrays (it says so in the minizip header comments) if the system is unicode or something..?? there's something about it, that's why i'm casting it, but i have not been able to test it yet properly

2022-05-01 10:47 UTC, Rackover commented on src/common/utils/io.cpp
>  		return std::ifstream(file).good();
i think it's not really same thing, file_exists is misnamed but i suppose ifstream also checks if the file can be accessed, as in not read-locked by another process?

2022-05-01 11:35 UTC, Rackover commented
If someone knows how to merge this against latest develop without diffing the entire file because of line endings or whatever, let me know

2022-05-01 17:10 UTC, diamante0018 commented on src/common/utils/nt.cpp
> +		mbstowcs_s(&result, &wc[0], c_size, narrow_command_line.data(), _TRUNCATE);
I would have wished to be utils::string::convert but I think this works just as fine.
I had to use the _s version to suppress compile warnings about the non _s version being unsafe.
Same old story with msvc.

2022-05-09 07:07 UTC, momo5502 commented
Tbh, I don't like this PR. Using com for zip is ugly af.

2022-05-25 21:02 UTC, mjkzy commented
bump on this PR, seems to be a pretty important issue still.

2022-08-24 10:30 UTC, momo5502 commented
Seems not necessary anymore due to !409

2022-08-24 10:30 UTC, closed without merging