Improve dev setup
XLabsProject/launcher pull request #96
Opened 2021-09-25 21:05 UTC by Laupetin

This PR aims to make the setup for development work out of the box and only make use of files local to the project folder to avoid conflicts with data from live environment.

This also features changes to the way the logic around the entrypoint is structured since this felt more natural to me to have for including variables that controls the paths.

2021-09-25 21:31 UTC, Laupetin commented
I gotta admit i'm not entirely sure if i may have broken the release pipeline by changing paths a bit.
Maybe there's a few things you would setup differently. Feel free to edit.

2021-09-30 07:06 UTC, momo5502 requested changes

2021-09-30 07:06 UTC, momo5502 commented on deps/premake/cef.lua
> +			"copy /y \"%{wks.location}..\\deps\\cef\\Resources\\*.dat\" \"%{wks.location}runtime\\data\\cef\\%{cfg.buildcfg}\\\"",
Are postbuild commands gonna retrigger if the project itself has not changed? Meaning when i switch from debug to release, back to debug, the binaries would not be copied over. And even if, binaries will need to be copied again and again. Make it quite unportable to work with debug builds.

2021-09-30 07:06 UTC, momo5502 commented on src/common/utils/properties.cpp
> +    Properties::Properties()
Bad naming convention

2021-09-30 07:06 UTC, momo5502 commented on src/launcher/cef/cef_ui.cpp
> +		CefString(&settings.cache_path) = this->path_ / "user/cef-data/cache";
Good addition

2021-09-30 07:06 UTC, momo5502 commented on src/launcher/launcher.hpp
> +class Launcher
Why is this a class?

2021-09-30 07:06 UTC, momo5502 commented on src/launcher/launcher.hpp
> +class Launcher
Should be a namespace

2022-01-16 16:55 UTC, Laupetin commented on src/launcher/launcher.hpp
> +class Launcher
True, i changed it

2022-01-16 16:56 UTC, Laupetin commented on src/common/utils/properties.cpp
> +    Properties::Properties()
Yep i confused the naming conventions with some other project apparently, i changed them at all commented places

2022-01-16 16:56 UTC, Laupetin commented on src/launcher/launcher.hpp
> +
Due to it being methods of the class in that case but since it's now a namespace like commented below they are now gone from the header

2022-01-16 16:58 UTC, Laupetin commented on src/launcher/launcher.hpp
> +    inline static std::filesystem::path download_path;
Inline specifier allows to only define them inside the header instead of declaring them in the header and defining them in the source file. Now since this isn't a class anymore those are moved to the source file and there is no inline specifier used anymore.

2022-01-16 16:58 UTC, Laupetin commented on src/launcher/launcher.hpp
> +    static std::string GetAppdataPath();
👍 Changed

2022-01-16 17:10 UTC, Laupetin commented on deps/premake/cef.lua
> +			"copy /y \"%{wks.location}..\\deps\\cef\\Resources\\*.dat\" \"%{wks.location}runtime\\data\\cef\\%{cfg.buildcfg}\\\"",
Files will only be copied over when there was a change inside the `cef` project. 

Meaning if compile in Debug -> Swap to Release -> Swap to Debug
they will not be copied again.

However the cef files are copied into a directory depending on the build cfg (so Debug/Release subfolder).
If you compile in Debug, you will still need to compile in Release making sure you cannot run without having these files being placed.

I'm not exactly sure what you mean with making it unportable to work with debug builds.
The files are not being copied there over and over again, nor is there a chance you start with these files missing from the expected location (unless they are being manually deleted).

I guess i do not exactly understand what the problem is.

2023-03-14 11:57 UTC, closed without merging